nameOverride:
fullnameOverride:

image:
  repository: y4m4/s3www
  tag: v0.9.0
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

config:
  bucket: files
  endpoint: http://minio:9000
  address: 0.0.0.0:8080
  accessKey: minioadmin
  secretKey: minioadmin
  port: 8080

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics
    port: http

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: s3www.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

podSecurityContext:
  fsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: false

healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3