apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "s3www.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "s3www.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "s3www.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          env:
            - name: S3WWW_ENDPOINT
              value: {{ .Values.config.endpoint }}
            - name: S3WWW_BUCKET
              value: {{ .Values.config.bucket }}
            - name: S3WWW_ACCESS_KEY
              value: {{ .Values.config.accessKey }}
            - name: S3WWW_SECRET_KEY
              value: {{ .Values.config.secretKey }}
            - name: S3WWW_ADDRESS
              value: {{ .Values.config.address }}
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}