{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "s3www.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.monitoring.serviceMonitor.port }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
    scheme: http
{{- end }}